services:
  pg-database:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ny_taxi
    volumes:
      - /Users/anoodeep/Documents/Study_Materials/DE_Zoomcamp/ny_taxi_postgres_data:/var/lib/postgresql/data:rw
    ports:
      - 5433:5432
  pgadmin:
    image: dpage/pgadmin4:8.14.0
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    volumes:
      - /Users/anoodeep/Documents/Study_Materials/DE_Zoomcamp/pgadmin_data:/var/lib/pgadmin:rw
    ports:
      - 8080:80
