services:
  psql_server:
    image: postgres:17.4 # latest image at the time of this commit
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ny_taxi
    volumes:
      - ./docker_volumes/psql_data:/var/lib/postgresql/data:rw
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 30s

  pgadmin:
    image: dpage/pgadmin4:9.1.0 # latest image at the time of this commit
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    volumes:
      - ./docker_volumes/pgadmin_data:/var/lib/pgadmin:rw
    ports:
      - 8080:80
    depends_on:
      psql_server:
        condition: service_started
