services:
  pg-database:
    image: postgres:17.4
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ny_taxi
    volumes:
      - ./ny_taxi_postgres_data:/var/lib/postgresql/data:rw
    ports:
      - 5433:5432

  pgadmin:
    image: dpage/pgadmin4:9.1.0
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin:rw
    ports:
      - 8080:80

  # taxi-ingest:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   volumes:
  #     - .:/app
  #   entrypoint: ["python", "ingest_data.py"]
